#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NUM_SAMPLES 4
#define MAX_SAMPLE_LENGTH 25000
#define QUARTER_NOTE_STEPS 32
#define QUARTER_NOTE_STEPS_SEQUENCEABLE 8
#define MAX_TIME_SIGNATURE 8

#endif