M48
; DRILL file {KiCad 7.0.2} date Tue Jul  9 13:38:02 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-09T13:38:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.8545Y-2.3244
X6.0455Y-2.3244
T2
X5.8427Y-2.2051
X6.0573Y-2.2051
T0
M30
