M48
; DRILL file {KiCad 7.0.2} date Wed Aug 30 16:49:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-30T16:49:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X5.5262Y-3.0858
X5.7171Y-3.0858
T2
X5.5144Y-2.9665
X5.7289Y-2.9665
T3
X3.3071Y-2.126
X3.3071Y-4.9606
X7.7165Y-2.126
X7.7165Y-4.9606
T0
M30
